//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lanchat.Terminal.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Lanchat.Terminal.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Ui_HelloMessage {
            get {
                return ResourceManager.GetString("Ui_HelloMessage", resourceCulture);
            }
        }
        
        internal static string Manual_Connect {
            get {
                return ResourceManager.GetString("Manual_Connect", resourceCulture);
            }
        }
        
        internal static string Manual_Help {
            get {
                return ResourceManager.GetString("Manual_Help", resourceCulture);
            }
        }
        
        internal static string Ui_Motd {
            get {
                return ResourceManager.GetString("Ui_Motd", resourceCulture);
            }
        }
        
        internal static string Ui_WindowTitle {
            get {
                return ResourceManager.GetString("Ui_WindowTitle", resourceCulture);
            }
        }
        
        internal static string Info_ConnectionAttempt {
            get {
                return ResourceManager.GetString("Info_ConnectionAttempt", resourceCulture);
            }
        }
        
        internal static string Info_IncorrectValues {
            get {
                return ResourceManager.GetString("Info_IncorrectValues", resourceCulture);
            }
        }
        
        internal static string Info_ManualNotFound {
            get {
                return ResourceManager.GetString("Info_ManualNotFound", resourceCulture);
            }
        }
        
        internal static string Manual_Nick {
            get {
                return ResourceManager.GetString("Manual_Nick", resourceCulture);
            }
        }
        
        internal static string Info_WrongNickname {
            get {
                return ResourceManager.GetString("Info_WrongNickname", resourceCulture);
            }
        }
        
        internal static string Info_SelfNicknameChanged {
            get {
                return ResourceManager.GetString("Info_SelfNicknameChanged", resourceCulture);
            }
        }
        
        internal static string Manual_Disconnect {
            get {
                return ResourceManager.GetString("Manual_Disconnect", resourceCulture);
            }
        }
        
        internal static string Manual_Block {
            get {
                return ResourceManager.GetString("Manual_Block", resourceCulture);
            }
        }
        
        internal static string Manual_Unblock {
            get {
                return ResourceManager.GetString("Manual_Unblock", resourceCulture);
            }
        }
        
        internal static string Info_NotFound {
            get {
                return ResourceManager.GetString("Info_NotFound", resourceCulture);
            }
        }
        
        internal static string Info_Blocked {
            get {
                return ResourceManager.GetString("Info_Blocked", resourceCulture);
            }
        }
        
        internal static string Info_Unblocked {
            get {
                return ResourceManager.GetString("Info_Unblocked", resourceCulture);
            }
        }
        
        internal static string Info_BlockedList {
            get {
                return ResourceManager.GetString("Info_BlockedList", resourceCulture);
            }
        }
        
        internal static string Info_ConnectedList {
            get {
                return ResourceManager.GetString("Info_ConnectedList", resourceCulture);
            }
        }
        
        internal static string Info_Disconnected {
            get {
                return ResourceManager.GetString("Info_Disconnected", resourceCulture);
            }
        }
        
        internal static string Info_Reconnecting {
            get {
                return ResourceManager.GetString("Info_Reconnecting", resourceCulture);
            }
        }
        
        internal static string Info_Connected {
            get {
                return ResourceManager.GetString("Info_Connected", resourceCulture);
            }
        }
        
        internal static string Info_ConnectionError {
            get {
                return ResourceManager.GetString("Info_ConnectionError", resourceCulture);
            }
        }
        
        internal static string Info_NicknameChanged {
            get {
                return ResourceManager.GetString("Info_NicknameChanged", resourceCulture);
            }
        }
        
        internal static string Manual_M {
            get {
                return ResourceManager.GetString("Manual_M", resourceCulture);
            }
        }
        
        internal static string Info_PortBusy {
            get {
                return ResourceManager.GetString("Info_PortBusy", resourceCulture);
            }
        }
        
        internal static string Info_CannotConnect {
            get {
                return ResourceManager.GetString("Info_CannotConnect", resourceCulture);
            }
        }
        
        internal static string Info_DetectedList {
            get {
                return ResourceManager.GetString("Info_DetectedList", resourceCulture);
            }
        }
    }
}
