//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lanchat.Terminal.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lanchat.Terminal.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting connect to.
        /// </summary>
        internal static string _ConnectionAttempt {
            get {
                return ResourceManager.GetString("_ConnectionAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug mode enabled.
        /// </summary>
        internal static string _DebugMode {
            get {
                return ResourceManager.GetString("_DebugMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect values.
        /// </summary>
        internal static string _IncorrectValues {
            get {
                return ResourceManager.GetString("_IncorrectValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual not found.
        /// </summary>
        internal static string _ManualNotFound {
            get {
                return ResourceManager.GetString("_ManualNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    __                 __        __  ___ 
        ///  / /  ___ ____  ____/ /  ___ _/ /_|_  |
        /// / /__/ _ `/ _ \/ __/ _ \/ _ `/ __/ __/ 
        ////____/\_,_/_//_/\__/_//_/\_,_/\__/____/
        ///.
        /// </summary>
        internal static string HelloAsci {
            get {
                return ResourceManager.GetString("HelloAsci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax: /connect &lt;ip&gt;.
        /// </summary>
        internal static string Manual_Connect {
            get {
                return ResourceManager.GetString("Manual_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Commands list:
        ///connect
        ///help
        ///list
        ///Try /help &lt;command&gt;.
        /// </summary>
        internal static string Manual_Help {
            get {
                return ResourceManager.GetString("Manual_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://tofu.ovh.
        /// </summary>
        internal static string PageLink {
            get {
                return ResourceManager.GetString("PageLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; .
        /// </summary>
        internal static string PromptIndicator_Default {
            get {
                return ResourceManager.GetString("PromptIndicator_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lanchat.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
